# Generated by Django 6.0.6 on 2026-06-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Control",
                "verbose_name_plural": "System Control",
            },
        ),
        migrations.AddField(
            model_name="timetable",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.program",
            ),
            preserve_default=False,
        ),
    ]
