# Generated by Django 6.0.6 on 2026-06-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_systemcontrol_timetable_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="course",
            name="is_mathematical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_technical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursedifficultyprediction",
            name="difficulty_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="availability_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.department",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="employee_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="max_hours_per_day",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="max_hours_per_week",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="program",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="level",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Lecture Hall", "Lecture Hall"),
                    ("Laboratory", "Laboratory"),
                    ("ODL Room", "ODL Room"),
                    ("Computer Lab", "Computer Lab"),
                ],
                default="Lecture Hall",
                max_length=30,
            ),
        ),
    ]
