# Generated by Django 6.0.6 on 2026-06-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_passwordresetcode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresetcode",
            new_name="scheduling__code_364989_idx",
            old_name="scheduling_prc_code_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresetcode",
            new_name="scheduling__created_49d0e4_idx",
            old_name="scheduling_prc_created_idx",
        ),
        migrations.AlterField(
            model_name="timetable",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.lecturer",
            ),
        ),
    ]
