# Generated by Django 6.0.6 on 2026-06-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduling",
            "0006_rename_scheduling_prc_code_idx_scheduling__code_364989_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="program",
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="programs",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="scheduling.program"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="programs",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="scheduling.program"
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
