# Generated by Django 6.0.6 on 2026-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_alter_studentgroup_program_delete_behavior"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="programs",
        ),
        migrations.AddField(
            model_name="program",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_programs", to="scheduling.room"
            ),
        ),
    ]
