# Generated by Django 6.0.6 on 2026-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0009_remove_room_programs_program_rooms"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'scheduling_course'
                      AND column_name = 'student_count'
                ) THEN
                    ALTER TABLE scheduling_course ADD COLUMN student_count integer NOT NULL DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE scheduling_course DROP COLUMN IF EXISTS student_count;
            """,
        ),
    ]
