# Generated by Django 6.0.6 on 2026-06-29 04:03

from django.db import migrations, models
from django.db import connection


def add_field_if_not_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM information_schema.columns WHERE table_name = 'scheduling_course' AND column_name = 'student_count'")
        if not cursor.fetchone():
            schema_editor.add_field(
                apps.get_model("scheduling", "course"),
                models.PositiveIntegerField(default=0),
            )


def alter_program_level_if_needed(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM information_schema.columns WHERE table_name = 'scheduling_program' AND column_name = 'level'")
        if cursor.fetchone():
            schema_editor.execute("ALTER TABLE scheduling_program ALTER COLUMN level TYPE integer")


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0011_course_student_count_alter_lecturer_email"),
    ]

    operations = [
        migrations.RunPython(add_field_if_not_exists, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lecturer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="level",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
