# Generated by Django 6.0.6 on 2026-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0012_course_student_count_alter_lecturer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
